#!/bin/sh

if test -d /usr/local/cross/i686-pc-cygwin; then
  CROSSPATH=/usr/local/cross/i686-pc-cygwin/
else
  CROSSPATH=/usr/local/cygwin/i686-pc-cygwin/
fi
PATH=${CROSSPATH}/bin:${PATH}
CC=i686-pc-cygwin-gcc
AR=i686-pc-cygwin-ar
AS=i686-pc-cygwin-as
LD=i686-pc-cygwin-ld
RANLIB=i686-pc-cygwin-ranlib
DLLTOOL=i686-pc-cygwin-dlltool
WINDRES=i686-pc-cygwin-windres
# for gcc3 and later, use -mms-bitfields instead of -fnative-struct
CFLAGS="-O2 -g -I${CROSSPATH}/gtk/include -mno-cygwin -mpentium -fnative-struct"
LDFLAGS="-L${CROSSPATH}/gtk/lib -mno-cygwin"
export CC AS AR LD RANLIB DLLTOOL PATH CFLAGS LDFLAGS
dir=`dirname $0`
${dir}/configure --host=i686-pc-cygwin --build=i686-pc-linux-gnu --disable-nls $*
