/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_aboutwindow (void);
GtkWidget* create_newconfigwindow (void);
GtkWidget* create_errordialog (void);
GtkWidget* create_specwindow (void);
GtkWidget* create_scopewindow (void);
GtkWidget* create_receivewindow (void);
GtkWidget* create_p3dwindow (void);
