.\" Copyright 2000 Thomas Sailer (sailer@ife.ee.ethz.ch)
.\" May be distributed under the GNU General Public License
.\"
.\" "
.TH SOUNDMODEMCONFIG 8 "1 August 2000" "SOUNDMODEM 0.2" "Linux AX.25 Utilities Manual"
.SH NAME
soundmodemconfig \- Soundcard modem configuration utility
.SH SYNOPSIS
.B soundmodemconfig
.B "[ \-sSRM ]"
.B "[\-v verbosity level]"
.B "[\-c configuration name]"


.SH DESCRIPTION
.B soundmodemconfig
is a GUI tool for creating a configuration file for soundmodem (8).
The default file name is /etc/ax25/soundmodem.conf, though
any other file name may be specified on the command line.


.SH "SEE ALSO"
.nf
.BR ifconfig "\ (8), " soundmodem "\ (8)"
.fi

.SH AUTHOR
soundmodemconfig was written by Thomas Sailer, HB9JNX/AE4WA (sailer@ife.ee.ethz.ch).
